import type { Event, Session } from "./types";

export const SAMPLE_SESSION_ID = "session-local-guard-preview";

export const SAMPLE_SESSIONS: Session[] = [
  {
    session_id: SAMPLE_SESSION_ID,
    actions: 6,
    current: true,
    status: "open",
    mode: "observe",
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_EVENTS: Event[] = [
  {
    id: "evt-prod-mutation-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "allow",
    reason_code: "judge_deny",
    reason: "Local judge flagged a production mutation as high risk.",
    created_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    risk_event: {
      type: "provider_operation",
      operation: "delete",
      operation_class: "write",
      environment: "production",
      command_summary: "kubectl delete deployment checkout-api -n production",
      signals: ["production", "mutation", "persistent_resource"],
      decision_stage: "judge_deny",
      judge_risk_level: "high",
      judge_categories: ["production_mutation"],
    },
  },
  {
    id: "evt-credential-read-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Read",
    decision: "allow",
    reason_code: "judge_deny",
    reason: "Local judge flagged credential access as high risk.",
    created_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    risk_event: {
      type: "credential_access",
      operation: "read",
      environment: "local",
      path_class: "~/.aws/credentials",
      command_summary: "Read local AWS credentials without explicit user intent",
      signals: ["credential_path", "credential_observed"],
      decision_stage: "judge_deny",
      judge_risk_level: "high",
      judge_categories: ["credential_access"],
    },
  },
  {
    id: "evt-admin-reindex-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "allow",
    reason_code: "judge_deny",
    reason: "Local judge flagged a risky staging admin mutation.",
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "network_write",
      operation_class: "write",
      environment: "staging",
      command_summary: "curl -X POST $PAYMENTS_ADMIN_URL/reindex",
      signals: ["network_call", "admin_endpoint"],
      decision_stage: "judge_deny",
      judge_duration_ms: 284,
      judge_risk_level: "high",
      judge_categories: ["admin_mutation"],
    },
  },
  {
    id: "evt-private-key-decrypt-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "allow",
    reason_code: "judge_deny",
    reason: "Local judge flagged an unfamiliar decryption command as high risk.",
    created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    risk_event: {
      type: "unknown",
      operation: "shell",
      operation_class: "unknown",
      environment: "local",
      command_summary: "openssl rsautl -decrypt -inkey private.pem -in payload.bin",
      signals: ["unknown_high_risk", "credential_observed"],
      decision_stage: "judge_deny",
      judge_risk_level: "high",
      judge_categories: ["credential_access"],
    },
  },
  {
    id: "evt-readme-allow-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Read",
    decision: "allow",
    reason_code: "judge_allow",
    reason: "Local judge assessed a workspace read as low risk.",
    created_at: new Date(Date.now() - 3.5 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "read",
      environment: "local",
      path_class: "workspace_file",
      command_summary: "Read README.md",
      signals: ["workspace_file", "documentation_read"],
      decision_stage: "judge_allow",
      judge_risk_level: "low",
    },
  },
  {
    id: "evt-bash-allow-001",
    session_id: SAMPLE_SESSION_ID,
    tool_name: "Bash",
    decision: "allow",
    reason_code: "judge_allow",
    reason: "Local judge allowed a low-risk read-only command.",
    created_at: new Date(Date.now() - 3.2 * 60 * 1000).toISOString(),
    risk_event: {
      type: "normal_tool_call",
      operation: "shell",
      operation_class: "read",
      environment: "local",
      command_summary: "git status --short",
      signals: ["known_safe_command", "local_workspace"],
      decision_stage: "judge_allow",
      judge_duration_ms: 142,
      judge_risk_level: "low",
    },
  },
];
