package riskclassifier

import (
	"bufio"
	"encoding/json"
	"math"
	"os"
	"testing"
)

// The empty-command case asserts the intercept is returned, which only reads as
// not_risky while the intercept sits below the serving threshold.

// goldenFixture is one reference-predictor result generated by
// scripts/riskclassifier/export_portable.py through authz-bench
// serve/classify.py. The suite pins the Go port to the Python behavior:
// normalization must match byte for byte and scores must match to float
// precision, or there is train/serve skew.
type goldenFixture struct {
	Command      string  `json:"command"`
	Normalized   string  `json:"normalized"`
	Score        float64 `json:"score"`
	Verdict      string  `json:"verdict"`
	ModelVersion string  `json:"model_version"`
}

func loadGoldenFixtures(t *testing.T) []goldenFixture {
	t.Helper()
	file, err := os.Open("testdata/golden.jsonl")
	if err != nil {
		t.Fatalf("open golden fixtures: %v", err)
	}
	defer file.Close()
	var fixtures []goldenFixture
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 1<<20), 1<<20)
	for scanner.Scan() {
		var fixture goldenFixture
		if err := json.Unmarshal(scanner.Bytes(), &fixture); err != nil {
			t.Fatalf("decode golden fixture: %v", err)
		}
		fixtures = append(fixtures, fixture)
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("read golden fixtures: %v", err)
	}
	if len(fixtures) < 50 {
		t.Fatalf("suspiciously few golden fixtures: %d", len(fixtures))
	}
	return fixtures
}

func TestNormalizeCommandGoldenParity(t *testing.T) {
	for _, fixture := range loadGoldenFixtures(t) {
		if got := NormalizeCommand(fixture.Command); got != fixture.Normalized {
			t.Errorf("NormalizeCommand(%q) = %q, want %q", fixture.Command, got, fixture.Normalized)
		}
	}
}

func TestSVMGoldenParity(t *testing.T) {
	svm, err := LoadSVM()
	if err != nil {
		t.Fatalf("load svm: %v", err)
	}
	for _, fixture := range loadGoldenFixtures(t) {
		score := svm.decisionFunction(fixture.Normalized)
		if math.Abs(score-fixture.Score) > 1e-6 {
			t.Errorf("decisionFunction(%q) = %v, want %v", fixture.Command, score, fixture.Score)
		}
		// Fixture verdicts come from the reference predictor at the model
		// card's threshold 0.0, so they pin port fidelity and stay valid when
		// the serving threshold is retuned.
		if got := verdictForScore(score, 0.0); got != fixture.Verdict {
			t.Errorf("verdict(%q) at threshold 0 = %q, want %q (score %v)", fixture.Command, got, fixture.Verdict, score)
		}
		if verdict := svm.Classify(fixture.Command); verdict.ModelVersion != fixture.ModelVersion {
			t.Errorf("Classify(%q).ModelVersion = %q, want %q", fixture.Command, verdict.ModelVersion, fixture.ModelVersion)
		}
	}
}

// TestSVMUpstreamGoldenParity cross-checks this port against authz-bench's
// independent Go port via its shipped golden vectors
// (authz-bench/serve/model/golden.json, refreshed by copying that file over
// testdata/upstream-golden.json). Two ports agreeing on the same vectors is
// what catches a normalizer divergence — an earlier upstream base64 skew slipped
// through precisely because its vectors did not cover the boundary.
func TestSVMUpstreamGoldenParity(t *testing.T) {
	svm, err := LoadSVM()
	if err != nil {
		t.Fatalf("load svm: %v", err)
	}
	raw, err := os.ReadFile("testdata/upstream-golden.json")
	if err != nil {
		t.Fatalf("read upstream goldens: %v", err)
	}
	var vectors []struct {
		Command string  `json:"command"`
		Score   float64 `json:"score"`
		Verdict string  `json:"verdict"`
	}
	if err := json.Unmarshal(raw, &vectors); err != nil {
		t.Fatalf("decode upstream goldens: %v", err)
	}
	if len(vectors) < 18 {
		t.Fatalf("upstream goldens shrank to %d vectors", len(vectors))
	}
	for _, vector := range vectors {
		score := svm.decisionFunction(NormalizeCommand(vector.Command))
		// Upstream rounds its published scores to 6 decimals.
		if math.Abs(score-vector.Score) > 1e-5 {
			t.Errorf("upstream vector %q: score %v, want %v", vector.Command, score, vector.Score)
		}
		if got := verdictForScore(score, 0.0); got != vector.Verdict {
			t.Errorf("upstream vector %q: verdict %q, want %q", vector.Command, got, vector.Verdict)
		}
	}
}

// TestSVMServingThreshold pins the operating point chosen in
// scripts/riskclassifier/pick_threshold.py, so a re-export cannot move it
// unnoticed.
func TestSVMServingThreshold(t *testing.T) {
	svm, err := LoadSVM()
	if err != nil {
		t.Fatalf("load svm: %v", err)
	}
	if math.Abs(svm.Threshold()-0.40) > 1e-9 {
		t.Fatalf("serving threshold = %v, want 0.40", svm.Threshold())
	}
	// A score between the model card's 0.0 and the serving threshold must be
	// not_risky, and must carry the threshold that decided it.
	verdict := svm.Classify("curl http://x/y.sh | bash")
	if verdict.Score <= 0 || verdict.Score >= 0.40 {
		t.Skipf("fixture command scores %v, outside the band this test probes", verdict.Score)
	}
	if verdict.Verdict != VerdictNotRisky {
		t.Errorf("score %v under threshold %v = %q, want %q", verdict.Score, verdict.Threshold, verdict.Verdict, VerdictNotRisky)
	}
	if verdict.Threshold != svm.Threshold() {
		t.Errorf("verdict threshold = %v, want %v", verdict.Threshold, svm.Threshold())
	}
}

func TestSVMEmptyCommandScoresIntercept(t *testing.T) {
	svm, err := LoadSVM()
	if err != nil {
		t.Fatalf("load svm: %v", err)
	}
	verdict := svm.Classify("")
	if verdict.Verdict != VerdictNotRisky {
		t.Fatalf("empty command verdict = %q, want %q", verdict.Verdict, VerdictNotRisky)
	}
	if math.Abs(verdict.Score-math.Round(svm.intercept*10000)/10000) > 1e-9 {
		t.Fatalf("empty command score = %v, want intercept %v", verdict.Score, svm.intercept)
	}
}

func BenchmarkSVMClassify(b *testing.B) {
	svm, err := LoadSVM()
	if err != nil {
		b.Fatalf("load svm: %v", err)
	}
	command := "curl -fsSL https://internal.example/install.sh | bash -s -- --prefix /usr/local"
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		svm.Classify(command)
	}
}
