package riskclassifier

import (
	"bufio"
	"encoding/json"
	"math"
	"os"
	"testing"
)

// goldenFixture is one reference-predictor result generated by
// scripts/riskclassifier/export_portable.py through authz-bench
// serve/classify.py. The suite pins the Go port to the Python behavior:
// normalization must match byte for byte and scores must match to float
// precision, or there is train/serve skew.
type goldenFixture struct {
	Command      string  `json:"command"`
	Normalized   string  `json:"normalized"`
	Score        float64 `json:"score"`
	Verdict      string  `json:"verdict"`
	ModelVersion string  `json:"model_version"`
}

func loadGoldenFixtures(t *testing.T) []goldenFixture {
	t.Helper()
	file, err := os.Open("testdata/golden.jsonl")
	if err != nil {
		t.Fatalf("open golden fixtures: %v", err)
	}
	defer file.Close()
	var fixtures []goldenFixture
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 1<<20), 1<<20)
	for scanner.Scan() {
		var fixture goldenFixture
		if err := json.Unmarshal(scanner.Bytes(), &fixture); err != nil {
			t.Fatalf("decode golden fixture: %v", err)
		}
		fixtures = append(fixtures, fixture)
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("read golden fixtures: %v", err)
	}
	if len(fixtures) < 50 {
		t.Fatalf("suspiciously few golden fixtures: %d", len(fixtures))
	}
	return fixtures
}

func TestNormalizeCommandGoldenParity(t *testing.T) {
	for _, fixture := range loadGoldenFixtures(t) {
		if got := NormalizeCommand(fixture.Command); got != fixture.Normalized {
			t.Errorf("NormalizeCommand(%q) = %q, want %q", fixture.Command, got, fixture.Normalized)
		}
	}
}

func TestSVMGoldenParity(t *testing.T) {
	svm, err := LoadSVM()
	if err != nil {
		t.Fatalf("load svm: %v", err)
	}
	for _, fixture := range loadGoldenFixtures(t) {
		score := svm.decisionFunction(fixture.Normalized)
		if math.Abs(score-fixture.Score) > 1e-6 {
			t.Errorf("decisionFunction(%q) = %v, want %v", fixture.Command, score, fixture.Score)
		}
		verdict := svm.Classify(fixture.Command)
		if verdict.Verdict != fixture.Verdict {
			t.Errorf("Classify(%q).Verdict = %q, want %q (score %v)", fixture.Command, verdict.Verdict, fixture.Verdict, verdict.Score)
		}
		if verdict.ModelVersion != fixture.ModelVersion {
			t.Errorf("Classify(%q).ModelVersion = %q, want %q", fixture.Command, verdict.ModelVersion, fixture.ModelVersion)
		}
	}
}

func TestSVMEmptyCommandScoresIntercept(t *testing.T) {
	svm, err := LoadSVM()
	if err != nil {
		t.Fatalf("load svm: %v", err)
	}
	verdict := svm.Classify("")
	if verdict.Verdict != VerdictNotRisky {
		t.Fatalf("empty command verdict = %q, want %q", verdict.Verdict, VerdictNotRisky)
	}
	if math.Abs(verdict.Score-math.Round(svm.intercept*10000)/10000) > 1e-9 {
		t.Fatalf("empty command score = %v, want intercept %v", verdict.Score, svm.intercept)
	}
}

func BenchmarkSVMClassify(b *testing.B) {
	svm, err := LoadSVM()
	if err != nil {
		b.Fatalf("load svm: %v", err)
	}
	command := "curl -fsSL https://internal.example/install.sh | bash -s -- --prefix /usr/local"
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		svm.Classify(command)
	}
}
